# Generated by Django 4.2.16 on 2024-10-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_login_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='twofa_status',
            field=models.BooleanField(default=True),
        ),
    ]
