version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - DOLLAR_SIGN=${DOLLAR_SIGN}
    container_name: pongers_frontend
    volumes:
      - ./frontend/front_comp:/frontend/
    restart: always
    env_file:
      - .env
    networks:
      - pongers
    ports:
      - "8080:80"
    profiles:
      - nginx

  frontend-vite:
    build:
      context: .
      dockerfile: vite/Dockerfile
    container_name: pongers_vite
    # volumes:
    #   - ./vite:/app/
    restart: always
    env_file:
      - .env
    networks:
      - pongers
    ports:
      - "3000:3000"
    profiles:
      - vite
  
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: pongers_backend
    volumes:
      - ./backend/apps:/app/
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"

#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
#     environment:
#       - discovery.type=single-node
#     ports:
#       - "9200:9200"
#     volumes:
#       - elasticsearch-data:/usr/share/elasticsearch/data
    
#   logstash:
#     image: docker.elastic.co/logstash/logstash:7.15.0
#     volumes:
#       - ./logstash/pipeline:/usr/share/logstash/pipeline
#     ports:
#       - "5000:5000"
#     depends_on:
#       - elasticsearch
  
#   kibana:
#     image: docker.elastic.co/kibana/kibana:7.15.0
#     ports:
#       - "5601:5601"
#     depends_on:
#       - elasticsearch

# volumes:
#   elasticsearch-data:

networks:
  pongers: